version: "3"

services:
  web:
    image: learn-anything:patch
    depends_on:
      - "dynamo"
      - "mem"
    ports:
      - "3000:3000"
    networks:
      - back-tier

  dynamo:
    image: dwmkerr/dynamodb
    container_name: dynamo
    volumes:
      - ./docker-data/shared-local-instance.db:/opt/dynamodb/shared-local-instance.db
    entrypoint: ["java", "-jar", "DynamoDBLocal.jar", "-sharedDb"]
    ports: ["8000"]
    networks:
      - back-tier

  mem:
    image: memcached:1-alpine
    container_name: mem
    ports: ["11211"]
    networks:
      - back-tier

networks:
  back-tier:

